import { useContext } from "react";
import { userContext } from "../contexts/UserContext";
import { reportContext } from "../contexts/ReportContext";

import type { Debt, Report } from "../types/UserTypes";

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL

export async function addEntry(entry: Debt) {

    const { user } = useContext(userContext)
    const { setReport } = useContext(reportContext)

    const userId = user!._id
    const accessToken = await cookieStore.get("accessToken")    

    try {
        // Update the backend first since a change might get rendered even if the endpoint fails
        const res = await fetch(`${BACKEND_URL}/add-debt-entry`, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'POST',
            body: JSON.stringify({
                userId: userId,
                entry: entry
            })
        })

        const resBody = await res.json()

        if (res.ok) {

            // If res is okay, body should include the entry ID generated by the BE
            const updatedEntry = {...entry, _id: resBody._id}

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {

                const newReport = prevReport!
                const debtList = [...newReport.debt, updatedEntry]

                newReport.debt = debtList
                
                return newReport
            })
            return 0
        }

        // If response is not ok, the body should include a message from the BE stating the error        
        throw Error(resBody.message)
        
    } catch (e) {

        console.log(e)
        return 1
    }
}

export async function updateEntry(entry: Debt) {

    const { user } = useContext(userContext)
    const { setReport } = useContext(reportContext)

    const userId = user!._id
    const accessToken = await cookieStore.get("accessToken")    

    try {
        // Update the backend first since a change might get rendered even if the endpoint fails
        const res = await fetch(`${BACKEND_URL}/update-debt-entry`, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'PUT',
            body: JSON.stringify({
                userId: userId,
                entry: entry
            })
        })

        if (res.ok) {

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {

                const newReport = prevReport!
                const indexToReplace = newReport.debt.findIndex((e) => e._id === entry._id)                

                newReport.debt[indexToReplace] = {...entry}                
                
                return newReport
            })
            return 0
        }

        // If response is not ok, the body should include a message from the BE stating the error
        const errorMessage = (await res.json()).message
        throw Error(errorMessage)
        
    } catch (e) {

        console.log(e)
        return 1
    }
}

export async function deleteEntry(entry: Debt) {

    const { user } = useContext(userContext)
    const { setReport } = useContext(reportContext)

    const userId = user!._id
    const accessToken = await cookieStore.get("accessToken")    

    try {
        // Update the backend first since a change might get rendered even if the endpoint fails
        const res = await fetch(`${BACKEND_URL}/delete-debt-entry`, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'DELETE',
            body: JSON.stringify({
                userId: userId,
                entry: entry
            })
        })

        if (res.ok) {

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {

                const newReport = prevReport!
                const indexToDelete = newReport.debt.findIndex((e) => e._id === entry._id)
                
                let newDebtList = []

                switch (indexToDelete) {
                    case 0:
                        newDebtList = newReport.debt.slice(1)
                        break
                    case newReport.debt.length - 1:
                        newDebtList = newReport.debt.slice(0, newReport.debt.length - 2)
                        break
                    default:
                        newDebtList = [
                            ...newReport.debt.slice(0, indexToDelete), 
                            ...newReport.debt.slice(indexToDelete + 1)
                        ]
                        break
                }                
                
                newReport.debt = newDebtList

                return newReport
            })
            
            return 0
        }

        // If response is not ok, the body should include a message from the BE stating the error
        const errorMessage = (await res.json()).message
        throw Error(errorMessage)
        
    } catch (e) {

        console.log(e)
        return 1
    }   
}