import { useContext } from "react";
import { userContext } from "../contexts/UserContext";
import { reportContext } from "../contexts/ReportContext";

import type { MonthlyDue } from "../types/UserTypes";

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL

export async function addEntry(entry: MonthlyDue) {

    const { user } = useContext(userContext)
    const { setReport } = useContext(reportContext)

    const userId = user!._id
    const accessToken = await cookieStore.get("accessToken")    

    try {
        // Update the backend first since a change might get rendered even if the endpoint fails
        const res = await fetch(`${BACKEND_URL}/add-monthly-due-entry`, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'POST',
            body: JSON.stringify({
                userId: userId,
                entry: entry
            })
        })

        const resBody = await res.json()

        if (res.ok) {

            // If res is okay, body should include the entry ID generated by the BE
            const updatedEntry = {...entry, _id: resBody._id}

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {
                
                const newEntries = [...prevReport!.monthlyDue, updatedEntry]                
                
                return {...prevReport!, monthlyDue: newEntries }
            })

            return 0
        }

        // If response is not ok, the body should include a message from the BE stating the error        
        throw Error(resBody.message)
        
    } catch (e) {

        console.log(e)
        return 1
    }
}

export async function updateEntry(entry: MonthlyDue) {

    const { user } = useContext(userContext)
    const { setReport } = useContext(reportContext)

    const userId = user!._id
    const accessToken = await cookieStore.get("accessToken")    

    try {
        // Update the backend first since a change might get rendered even if the endpoint fails
        const res = await fetch(`${BACKEND_URL}/update-monthly-due-entry`, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'POST',
            body: JSON.stringify({
                userId: userId,
                entry: entry
            })
        })

        const resBody = await res.json()

        if (res.ok) {                        

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {
                
                const newReport = prevReport!
                const indexToReplace = newReport.monthlyDue.findIndex((e) => e._id === entry._id)                

                newReport.monthlyDue[indexToReplace] = { ...entry }                 
                
                return newReport
            })
            
            return 0
        }

        // If response is not ok, the body should include a message from the BE stating the error        
        throw Error(resBody.message)
        
    } catch (e) {

        console.log(e)
        return 1
    }
}

export async function deleteEntry(entry: MonthlyDue) {

    const { user } = useContext(userContext)
    const { setReport } = useContext(reportContext)

    const userId = user!._id
    const accessToken = await cookieStore.get("accessToken")    

    try {
        // Update the backend first since a change might get rendered even if the endpoint fails
        const res = await fetch(`${BACKEND_URL}/delete-monthly-due-entry`, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'DELETE',
            body: JSON.stringify({
                userId: userId,
                entry: entry
            })
        })

        if (res.ok) {

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {
                
                const indexToDelete = prevReport!.monthlyDue.findIndex((e) => e._id === entry._id)
                
                let newMonthlyDueList = []

                switch (indexToDelete) {
                    case 0:
                        newMonthlyDueList = prevReport!.monthlyDue.slice(1)
                        break
                    case prevReport!.monthlyDue.length - 1:
                        newMonthlyDueList = prevReport!.monthlyDue.slice(0, prevReport!.monthlyDue.length - 2)
                        break
                    default:
                        newMonthlyDueList = [
                            ...prevReport!.monthlyDue.slice(0, indexToDelete), 
                            ...prevReport!.monthlyDue.slice(indexToDelete + 1)
                        ]
                        break
                }                                

                return {...prevReport!, monthlyDue: newMonthlyDueList}
            })
            
            return 0
        }

        // If response is not ok, the body should include a message from the BE stating the error
        const errorMessage = (await res.json()).message
        throw Error(errorMessage)
        
    } catch (e) {

        console.log(e)
        return 1
    }       
}