import { useContext } from "react";
import { userContext } from "../contexts/UserContext";
import { reportContext } from "../contexts/ReportContext";

import type { Report, TrackerEntry, User } from "../types/UserTypes";
import type useDataCache from "../hooks/useDataCache";

// !! These functions expect a user data to be stored in UserContext !!

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL

/* FIXME: Error handling for non-existent API is not handled.
    The current error handling for the APIs purely rely on an error message returned by the backend
    A situation where nothing is returned at all is not handled
*/

/**
 * Adds a new entry to the user's income or expense tracker for the current month
 * @param {TrackerEntry} entry - an object holding the values for the new entry
 * @param {string} type - a string that specifies which tracker list this entry goes to. Can either be `"income"` or `"expense"`
 * @returns 'message' - "success" if the entry update is successful, otherwise returns an error reason message.
 */
export async function addEntry(entry: TrackerEntry, type: "income" | "expense", cache: useDataCache) {

    try {        
        const userId = cache.user._id 
        const accessToken = await cookieStore.get("accessToken")        
        console.log("Got here")
        const res = await fetch(`${BACKEND_URL}/add-tracker-entry`, {
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'POST',
            body: JSON.stringify({
                userId: userId,
                type: type,
                entry: entry
            })
        })
        console.log("Got here")
        const resBody = await res.json()

        console.log(resBody)

        if (res.ok) {            

            // If res is okay, body should include the entry ID generated by the BE
            const updatedEntry = {...entry, _id: resBody._id}

            // Once backend is updated, update the cached data and render
            const oldEntries = (type === "income") ? cache.report.income : cache.report.expense                
            const newEntries = [...oldEntries, updatedEntry]   
            cache.report = {...cache.report, [(type === "income" ? "Income" : "Expense")]: newEntries }

            return "success"
        }

        // If response is not ok, the body should include a message from the BE stating the error        
        throw Error(resBody.message)
        
    } catch (e) {

        //console.log(e)
        return e as string
    }
}

/**
 * Updates an entry in the user's specified tracker list for the current month
 * @param {TrackerEntry} entry - an object containing the ID of the entry to be updated and its new values
 * @param {string} type - a string that specifies which tracker list to do the operation in. Can either be `"income"` or `"expense"`
 * @returns 'message' - "success" if the entry update is successful, otherwise returns an error reason message.
 */
export async function updateEntry(entry: TrackerEntry, type: "income" | "expense") {

    try {

        const { user } = useContext(userContext)
        const { setReport } = useContext(reportContext)

        const userId = user!._id        
        const accessToken = await cookieStore.get("accessToken")           

        const res = await fetch(`${BACKEND_URL}/update-tracker-entry`, {
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'PUT',
            body: JSON.stringify({
                userId: userId,
                type: type,
                entry: entry
            })
        })

        const resBody = await res.json()

        if (res.ok) {                        

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {

                const newReport = prevReport!
                const indexToReplace = newReport[type].findIndex((e) => e._id === entry._id)                

                newReport[type][indexToReplace] = { ...entry }                 
                
                return newReport
            })
            
            return "success"
        }

        // If response is not ok, the body should include a message from the BE stating the error        
        throw Error(resBody.message)
        
    } catch (e) {

        return e as string
    }
}

/**
 * Deletes an entry in the user's specified tracker list for the current month
 * @param {string} entryId - a string representing the entry's unique ID
 * @param {string} type - a string that specifies which tracker list to do the operation in. Can either be `"income"` or `"expense"`
 * @returns 'message' - "success" if the entry update is successful, otherwise returns an error reason message.
 */
export async function deleteEntry(entryId: string, type: "income" | "expense") {

    try {

        const { user } = useContext(userContext)
        const { setReport } = useContext(reportContext)

        const userId = user!._id        
        const accessToken = await cookieStore.get("accessToken")   

        const res = await fetch(`${BACKEND_URL}/delete-tracker-entry`, {
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'DELETE',
            body: JSON.stringify({
                userId: userId,
                type: type,
                entryId: entryId
            })
        })

        if (res.ok) {

            // Once backend is updated, update the cached data and render
            setReport(prevReport => {
                
                const indexToDelete = prevReport![type].findIndex((e) => e._id === entryId)
                
                let newTrackerList = []

                switch (indexToDelete) {
                    case 0:
                        newTrackerList = prevReport![type].slice(1)
                        break
                    case prevReport![type].length - 1:
                        newTrackerList = prevReport![type].slice(0, prevReport![type].length - 2)
                        break
                    default:
                        newTrackerList = [
                            ...prevReport![type].slice(0, indexToDelete), 
                            ...prevReport![type].slice(indexToDelete + 1)
                        ]
                        break
                }                                

                return {...prevReport!, [type]: newTrackerList}
            })
            
            return "success"
        }

        // If response is not ok, the body should include a message from the BE stating the error
        const errorMessage = (await res.json()).message
        throw Error(errorMessage)
        
    } catch (e) {

        console.log(e)
        return e as string
    }   
}