import type { TrackerEntry } from "../types/UserTypes";
import type useDataCache from "../hooks/useDataCache";

// !! These functions expect a user data to be stored in UserContext !!

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL

/**
 * Adds a new entry to the user's income or expense tracker for the current month
 * @param {TrackerEntry} entry - an object holding the values for the new entry
 * @param {string} type - a string that specifies which tracker list this entry goes to. Can either be `"income"` or `"expense"`
 * @returns 'message' - "success" if the entry update is successful, otherwise returns an error reason message.
 */
export async function addEntry(entry: TrackerEntry, type: "income" | "expense", cache: useDataCache) {

    try {        

        const userId = cache.user._id 
        const accessToken = await cookieStore.get("accessToken")        
        
        const res = await fetch(`${BACKEND_URL}/add-tracker-entry`, {
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'POST',
            body: JSON.stringify({
                userId: userId,
                type: type,
                entry: entry
            })
        })

        const resBody = await res.json()
 
        if (res.ok) {            

            // If res is okay, body should include the entry ID generated by the BE
            const updatedEntry = {...entry, _id: resBody._id}

            // Once backend is updated, update the cached data and render
            const oldEntries = (type === "income") ? cache.report.income : cache.report.expense                
            const newEntries = [...oldEntries, updatedEntry]   
            cache.report = {...cache.report, [(type === "income" ? "Income" : "Expense")]: newEntries }

            return "success"
        }

        // If response is not ok, the body should include a message from the BE stating the error        
        throw Error(resBody.message)
        
    } catch (e) {

        if (["SyntaxError", "TypeError"].includes((e as Error).name)) {

            return "Failed to fetch from servers. Please try again."
        }
        
        return (e as Error).message
    }
}

/**
 * Updates an entry in the user's specified tracker list for the current month
 * @param {TrackerEntry} entry - an object containing the ID of the entry to be updated and its new values
 * @param {string} type - a string that specifies which tracker list to do the operation in. Can either be `"income"` or `"expense"`
 * @returns 'message' - "success" if the entry update is successful, otherwise returns an error reason message.
 */
export async function updateEntry(entry: TrackerEntry, type: "income" | "expense", cache: useDataCache) {

    try {

        const userId = cache.user._id  
        const accessToken = await cookieStore.get("accessToken")           

        const res = await fetch(`${BACKEND_URL}/update-tracker-entry`, {
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'PUT',
            body: JSON.stringify({
                userId: userId,
                type: type,
                entry: entry
            })
        })

        const resBody = await res.json()

        if (res.ok) {                        

            // Once backend is updated, update the cached data and render
            const newReport = {...cache.report}
            const indexToReplace = cache.report[type].findIndex((e) => e._id === entry._id)      
            
            newReport[type][indexToReplace] = { ...entry }
            cache.report = newReport
            
            return "success"
        }

        // If response is not ok, the body should include a message from the BE stating the error        
        throw Error(resBody.message)
        
    } catch (e) {

        if (["SyntaxError", "TypeError"].includes((e as Error).name)) {

            return "Failed to fetch from servers. Please try again."
        }
        
        return (e as Error).message
    }
}

/**
 * Deletes an entry in the user's specified tracker list for the current month
 * @param {string} entryId - a string representing the entry's unique ID
 * @param {string} type - a string that specifies which tracker list to do the operation in. Can either be `"income"` or `"expense"`
 * @returns 'message' - "success" if the entry update is successful, otherwise returns an error reason message.
 */
export async function deleteEntry(entryId: string, type: "income" | "expense", cache: useDataCache) {

    try {

        const userId = cache.user._id       
        const accessToken = await cookieStore.get("accessToken")   

        const res = await fetch(`${BACKEND_URL}/delete-tracker-entry`, {
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${accessToken}`
            },
            method: 'DELETE',
            body: JSON.stringify({
                userId: userId,
                type: type,
                entryId: entryId
            })
        })

        if (res.ok) {

            // Once backend is updated, update the cached data and render
            const indexToDelete = cache.report[type].findIndex((e) => e._id === entryId)
            let newTrackerList = []

            switch (indexToDelete) {
                case 0:
                    newTrackerList = cache.report[type].slice(1)
                    break
                case cache.report[type].length - 1:
                    newTrackerList = cache.report[type].slice(0, cache.report[type].length - 2)
                    break
                default:
                    newTrackerList = [
                        ...cache.report[type].slice(0, indexToDelete), 
                        ...cache.report[type].slice(indexToDelete + 1)
                    ]
                    break
            }                                

            cache.report = {...cache.report, [type]: newTrackerList}
            
            return "success"
        }

        // If response is not ok, the body should include a message from the BE stating the error
        const errorMessage = (await res.json()).message
        throw Error(errorMessage)
        
    } catch (e) {

        if (["SyntaxError", "TypeError"].includes((e as Error).name)) {

            return "Failed to fetch from servers. Please try again."
        }
        
        return (e as Error).message
    }
}